### ISSUE TITLE
Vital http://docs.ractivejs.org/latest/migrating missing

### ISSUE THREAD

**Issue by lnryan** [ractivejs/ractivejs.github.io#77] opened 2017-06-22 06:49 UTC
This and other links referenced as guidance in the actual warning provided by ractive are inaccessible.

Please restore them.

**Comment by fskreuz** [comment] 2017-06-22 12:06
Hello! Docs have been moved to https://ractive.js.org/ and migrating should be under the Getting Started section. https://ractive.js.org/get-started/migrating/

**Comment by fskreuz** [comment] 2017-06-22 12:13
Closing in favor of https://github.com/ractivejs/ractivejs.github.io/issues/64 to document missing migrations. Current site does have to 0.8 and to 0.9.

**Closed by fskreuz** 2017-06-22 12:13 UTC
Labels: wontfix

**Comment by fskreuz** [comment] 2017-06-24 13:30
migration notes for older versions are now back https://ractive.js.org/support/#migrating-from-previous-versions . There's also an open issue about consolidating all warning and error messaging for Ractive https://github.com/ractivejs/ractive/issues/2733

**Comment by lnryan** [comment] 2017-06-25 16:46
Thanks for reviewing this, but unfortunately the "migrating" notes are insufficient. So I would kindly ask that you would reconsider making the original documentation for the versions that people are _still_ on available in _some_ format. It's completely not cool to just expect people to upgrade because you decided you like it better this way.

**Comment by fskreuz** [comment] 2017-06-25 17:23
> reconsider making the original documentation for the versions that people are still on available in some format until these 'migration' paths can actually produce a working migrations.

Old docs and their respective migration notes can be found here: https://ractive.js.org/v0.x

This was also mentioned in two other related threads:
- https://github.com/ractivejs/ractive/issues/3013#issue-237729298
- https://github.com/ractivejs/ractivejs.github.io/issues/54#issuecomment-310288740

> It's completely not cool to just expect people to upgrade on the spot because you decided to remove the original documentation for the version they're on.

[There have been several discussions already about overhauling the docs](https://github.com/ractivejs/ractivejs.github.io/issues/54#issuecomment-310369126):

- https://github.com/ractivejs/ractive/issues/2857
- https://github.com/ractivejs/ractive/pull/2747
- https://github.com/ractivejs/ractive/issues/2271#issuecomment-160825524

:)

**Comment by fskreuz** [comment] 2017-06-25 17:37
We'd be glad to help you migrate through versions. Should you find anything not working as intended, you can [file issues to ask questions in the Ractive repo](https://github.com/ractivejs/ractive/issues) and everyone else will (literally) jump in to help. 😁 

We're also available at [Gitter](https://gitter.im/ractivejs/ractive). A handful of us are online at any given moment in time.
